@extends('layouts.master')

@section('head')
  <link href="/css/bookStyle.css" type='text/css' rel='stylesheet'>
@stop

@section('content')
  <div id="irish">
    <table>
      <tr>
        <td><img src="/images/bookcover_square.png"></td>
        <td><div class="title"><a href="http://www.cambridge.org/us/academic/subjects/history/twentieth-century-british-history/ireland-and-irish-interwar-england"><i>Ireland and the Irish in Interwar England</i></a> (Cambridge: Cambridge University Press, 2014)</div></td>
      </tr>
      <tr>
        <td></td>
        <td>
          <div class="review">
          Reviews
          <ul>
            <li>Royal Historical Society&#8217;s 2015 <a href="http://royalhistsoc.org/prizes/whitfield-book-prize/" target='_blank'>Whitfield Prize</a> proxime accessit</li>
            <li>A &#8220;<a href="http://www.historytoday.com/history-today/books-year" target='_blank'>Book of the Year</a>,&#8221; <i>History Today</i> Vol. 64 12 December 2014</li>
            <li>&#8220;This is an engaging, well-considered work of genuine originality; it is, in my view,
            the best book out there on the Irish in Britain in any period.&#8221; (<a href="http://www.tandfonline.com/doi/pdf/10.1080/14780038.2015.1050887" target='_blank'>Donald MacRaild, &#8220;Ireland and the Irish in Interwar England by Mo Moulton,&#8221; <i>Cultural and Social History: The Journal of the Social History Society</i> Vol. 12 Issue 3 (2015)</a>)</li>
            <li>&#8220;Thought-provoking, richly evidenced and superbly structured, Moulton&#8217;s book is a tour de force, and a compelling argument for studying Irish and British history together.&#8221; (<a href="https://www.timeshighereducation.co.uk/books/ireland-and-the-irish-in-interwar-england-by-mo-moulton/2014093.article" target='_blank'>Niamh Gallagher, &#8220;Ireland and the Irish in Interwar England by Mo Moulton,&#8221; <i>Times Higher Education</i> 26 June 2014</a>)</li>
            <li>&#8220;A superb new book focusing on people often excluded from the Irish historical narrative.&#8221; (<a href="http://www.irishtimes.com/culture/books/entangled-connections-ireland-and-the-irish-in-interwar-england-1.1888307" target='_blank'>Enda Delaney, &#8220;Entangled connections: Ireland and the Irish in Interwar England,&#8221; <i>Irish Times</i> 9 August 2014</a>)</li>
            <li>&#8220;From sabotage campaigns to social clubs, and the misguided, over-romanticised notions of Ireland expounded in the English literary imagination, Moulton&#8217;s book is a captivating, informative twinning and unravelling of those aspects of social history which our two very separate (yet perpetually intermingling) nations shared between the wars.&#8221; (<a href="http://scholar.harvard.edu/files/momoulton/files/bolger_mail_on_sunday_review.pdf" target='_blank'>Dermot Bolger, &#8220;Separate and Together,&#8221; <i>Irish Mail on Sunday</i> 14 September 2014</a>)</li>
            <li>&#8220;Harvard historian Mo Moulton&#8217;s wonderful first book, Ireland and the Irish in Interwar England relies on a number of unfamiliar and fascinating archival sources and reveals a complex set of attitudes towards Ireland and Irishness in England during the 1920s and 1930s. One of the many things the book does well is to highlight how the political concerns outlined by Ukip are nothing new. It would be salutary for figures like Daniel Hannon and Mark Reckless to read this volume, since Moulton points out that, during the 1930s depression era, the benefits-scrounging migrant-bogeyman of the English imagination was often an Irishman.&#8221; (<a href="http://www.drb.ie/essays/enemies-within" target='_blank'>James Moran, &#8220;Enemies Within,&#8221; <i>Dublin Review of Books</i> Issue 63: January 2015</a>)</li>
            <li>&#8220;Ireland was a problem, Moulton convincingly argues, that required a continual effort of repression.&#8221; (<a href="http://www.historytoday.com/reviews/ireland-and-irish-interwar-england" target='_blank'>Lucy Delap, &#8220;Ireland and the Irish in Interwar England,&#8221; <i>History Today</i> Vol 65 Issue 3, March 2015</a>)</li>
            <li>&#8220;Most histories of Anglo-Irish relations during this period have concentrated on high politics and government papers. Moulton gives us descriptions of Gaelic League dances, letters written home by British troops serving in Ireland during the Anglo-Irish war, meetings of the Irish Literary Society and accounts of St. Patrick&#8217;s Day celebrations in inter-war England. But politics is not absent--especially in the period 1914-1921.&#8221; (<a href="http://www.tandfonline.com/doi/full/10.1080/13619462.2015.1031511" target='_blank'>Mary Daly, &#8220;Ireland and the Irish in Interwar England,&#8220; <i>Contemporary British History</i>, Vol. 29, No. 2, 2015</a>)</li>
            <li>&#8220;If you turn a map upside down or lay it on its side, it looks different for all that it otherwise presents the same information. By looking at how English society and how England&#8217;s Irish communities were reshaped by Ireland&#8217;s war of independence and at the heterogeneity of the Irish in England, Moulton offers a fresh point of view. The facts remain the same but the vantage point is a different one that sheds new light on the social history of the period.&#8221; (Bryan Fanning, &#8220;Ireland and the Irish in Interwar England,&#8221; <i>Studies</i>, Vol. 104 no. 415, Autumn 2015)</li>
            <li>&#8220;Moulton's multidisciplinary analysis is an invaluable study of the interconnectedness of both islands in a largely neglected period.&#8221; (Michaela Crawley, &#8220;Ireland and the Irish in Interwar England,&#8221; <a href="https://issuu.com/lpjis/docs/lpjis_2016__edited_draft_/1?e=1" target='_blank'><i>Liverpool Postgraduate Journal of Irish Studies</i></a>, Issue 1, 2016)</li>
            <li>&#8220;Nigel Farage, leader of Britain&#8217;s most successful nativist political party in the modern era, favours the Irish as &#8216;kith and kin&#8217; of the British. Compared to other Europeans, he would allow the Irish relatively privileged access to this United Kingdom&#8217;s sceptred isle. In a way this is odd, for few enmities are as long-lasting or as well known as that between Britain and Ireland. But of course, it makes sense once we recognise their entangled history. Mo Moulton&#8217;s sparklingly written and thoroughly researched book sheds much light on the inter-war period.&#8221; (Marc Mulholland, &#8220;Ireland and the Irish in Interwar England,&#8221; <i>Continuity and Change</i>, Vol. 30 no. 3, December 2015)</li>
            <li>&#8220;Moulton provides details on British soldiers&#8217; leisure activities in Ireland, consorting with the vestiges of the Anglo-Irish upper and middle classes in the revolutionary period. She reconstructs this world using their letters and diaries, providing the reader with an immediate and personal insight into a world that was largely lost after this time. Details of teas, dances and tennis parties are no trivial side-show to the main drama, but offer a glimpse into life for Protestant, urban, elite classes at a time of radical transition, and illuminate the conflict from both a personal and a British perspective. These viewpoints are often overlooked. The myriad details demonstrate the depth of research Moulton has conducted, often mining sources under-utilized by other historians. As far as possible, she allows men and women to speak for themselves as to how they experienced the conflict. This is a different perspective from most studies that focus on cabinet minutes, parliamentary debates or private papers of leading politicians. Moulton reveals how deeply engaged many Irish immigrants were in the spectrum of nationalist activities, from fund-raising dances to IRA cells. This surely calls into question why they do not appear in many major studies dedicated to the development of the nationalist movement in modern Ireland. Moulton makes a convincing case that they should be and, across classes and causes, there remained deep connections between Ireland and England, decades after the revolutionary years.&#8221; (Jennifer Redmond, &#8220;Ireland and the Irish in Interwar England,&#8221; <i>Family and Community History</i>, Vol. 19 no. 1, April 2016)</li>
            <li>&#8220;In <i>Ireland and the Irish in Interwar England</i>, Mo Moulton has drawn on an exhaustive body of archival material to offer an original and penetrating study of the relationship between Ireland and England during and after the Irish War of Independence. In the first half of the book Moulton makes a strong case for vising the conflict as a kind of British civil war. ... The second half of Moulton&#8217;s book makes the bigger contribution to the historiography, covering a range of Irish experiences of England in the interwar years. ... Moulton expertly handles the comparison with continental Europe, breaking with the tendency towards stressing similarity and instead making the case for the distinctiveness of the relationship between England and the Irish Free State.&#8221; (Stuart Aveyard, &#8220;Ireland and the Irish in Interwar England,&#8221; <i>Journal of British Studies</i>, Vol. 55, No. 1 (Jan. 2016), pp. 221-23)</li>
            <li>&#8220;Mo Moulton&#8217;s book is a very welcome addition to the historiography of the Irish in Britain. While there is a growing literature on the Victorian and post-Second World War eras, the inter-war period is relatively sparsely covered. Of the existing scholarship, most is centred on emigration from Ireland and/or the relationships between the elites of the two islands in the wake of the Anglo-Irish War. This book enormously expands its scope beyond these areas and is quite simply the most erudite book yet to appear on the topic.&#8221; (David Convery, &#8220;Ireland and the Irish in Interwar England,&#8221; <i>English Historical Review</i>, advance online access April 22, 2016)</li>
          </ul>
        </div>
        </td>
    </table>
  </div>


@stop

@section('body')

@stop
